---
title: "problemas en clase"
format: html
editor: visual
---

```{r}
library(tidyverse)
library(fpp3)
```

1

```{r}
global_economy
```

```{r}
pib_tsbl <- global_economy |>
  autoplot(GDP/Population) + theme(legend.position = "none")

pib_tsbl
```

¿Cómo ha sido la evolución de la economía de los países en el tiempo? 
como la gráfica lo muestra, la economía ha incrementado exponencialmente desde 1960 hasta la actualidad, mostrando un crecimiento mayor a partir de 1980 en adelante.

¿Cuál país tiene el mayor PIB per cápita?
Monaco

```{r}
global_economy |>
  mutate(gdp_per_capita = GDP/Population) |>
  select(-c(Code, Growth:Exports)) |>
  filter(Year %in% 2010:2017) |>
  as_tibble() |>
  group_by(Country) |>
  summarise(mean_gdppc = mean(gdp_per_capita, na.rm = TRUE)) |>
  arrange(desc(mean_gdppc))
```
2

```{r}
pibusa_tsbl <- global_economy |>
  filter(Country == "United States")

pibusa_tsbl
```
```{r}
pibusa_tsbl |>
  autoplot(log(GDP))
```

```{r}
pibmex_tsbl <- global_economy |>
  filter(Country == "Mexico")

pibmex_tsbl
```

```{r}
pibmex_tsbl |>
  autoplot(GDP)
```

```{r}
vic_elec |>
  autoplot(Demand)
```

3
```{r}
canadian_gas
```


```{r}
p5a <- canadian_gas %>% autoplot(Volume)+ 
  ggtitle("Producción de gas (datos reales)")

p5 <- canadian_gas %>% autoplot(box_cox(Volume,lambda = -0.5)) + ggtitle("Box-Cox, lambda = -0.5")

p6 <- canadian_gas %>% autoplot(box_cox(Volume,lambda = 0)) + ggtitle("Box-Cox, lambda = 0 (log)")

p7 <- canadian_gas %>% autoplot(box_cox(Volume,lambda = 0.1)) + ggtitle("Box-Cox, lambda = 0.1")

p8 <- canadian_gas %>% autoplot(box_cox(Volume,lambda = 1)) + ggtitle("Box-Cox, lambda = 1")

p5a
```

