---
title: "pronostico"
format: html
editor: visual
---

```{r}
library(tidyverse)
library(fpp3)
```

```{r}
mex <- global_economy |>
  filter(Country == "Mexico") |>
  drop_na() |>
  select(-c(Country, Code))

mex
```
```{r}
mex |>
  features(Growth, features = guerrero)

mex |>
  autoplot(box_cox(Growth, lambda = 0.7249))
```


```{r}
mex_fit <- mex |>
  model(
    media = MEAN(Growth),
    naive = NAIVE(box_cox(Growth, lambda = 0.7249)),
    drift = RW(box_cox(Growth, lambda = 0.7249) ~drift())
  )

mex_fit
```
## diagnóstico de residuos

```{r}
mex_fit |>
  augment() |>
    features(.innov, ljung_box, lag = 10, dof = 0)
```

Como el p-value de los tres modelos es mayor a nuestra $\alpha$; $p_{value} = 0.05$, **NO RECHAZAMOS** $H_0 : \text{"los residuos son ruido blanco"}$.

## MEDIA
```{r}
#| warning: false
mex_fit |>
  select(media) |>
  gg_tsresiduals()
```

##NAIVE
```{r}
#| warning: false
mex_fit |>
  select(naive) |>
  gg_tsresiduals()
```


#DRIFT
```{r}
#| warning: false
mex_fit |>
  select(drift) |>
  gg_tsresiduals()
```

## Forecast

```{r}
mex_fc <- mex_fit |>
  forecast(h = "6 years")

mex_fc

mex_fc |>
  autoplot(mex) + 
  facet_wrap(~.model) + 
  theme(legend.position = "none")
```

